repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: '23.9.1'
    hooks:
      - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: '1.6.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
